version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
       - gradle build -x test
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'
