spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    
sns:
  topic:
    arn: ${SNS_TOPIC_ARN}
